figures:
  # Required fields
  panel_dimensions_cm: {width: 11, height: 11}
  panel_margins_cm: {left: 1.5, bottom: 1.5, right: 0.5, top: 0.5}
  font_sizes_pt: {axes: 8, text: 6}
  # Optional fields
  ax_separation_cm: {x: 1.0, y: 1.0}
  scale_bar_pos_cm: {sep_cm: 0.5, offset_cm: 0.5, delta_text_cm: 0.5}
  panel_output: {directory: "output", format: "pdf", dpi: 600}
  debug_panel: {show: True, grid_res_cm: 0.5}
  # Custom fields
  colors:
    color_1: [0.8500, 0.3250, 0.0980]
    color_2: [0.4660, 0.6740, 0.1880]
    color_3: [0.4940, 0.1840, 0.5560]
    color_4: [0, 0.4470, 0.7410]